#Variables
ANTLR_JAR = ./interpreter_utils/antlr-4.13.2-complete.jar
GRAMMAR = scheme.g4
GEN_DIR = ./interpreter_utils
PYTHON = Python3
SCHEME_INTERPRETER = scheme.py
SCHEME_PROGRAM_DIR = ./scheme_programs
SCHEME_PROGRAM_ALL = all.scm
PROGRAM_INPUTS  = ./inout/input_files
PROGRAM_OUTPUTS = ./inout/output_files
PROGRAM_DIFF_OUTPUTS = ./inout/diff_output_files
#make all
all: setup options

options:
	@echo "clean: clean cache, antlr files generated and output files generated from tests"
	@echo "generate_tests: generate all tests with all the programs provided in ${SCHEME_PROGRAM_DIR}"
	@echo "run: run all.scm program, that has all the test files in one"

setup:
	@echo "Setting up miniScheme Interpreter ... "
	#java -jar ./interpreter_utils/antlr-4.13.2-complete.jar -Dlanguage=Python3 -visitor -no-listener -o ${GEN_DIR} ${GEN_DIR}/${GRAMMAR}
	mkdir -p ${PROGRAM_OUTPUTS}	#Create directory in case it does not exist

antlr:
	@echo "Generate Parser and Lexer from grammar {GRAMMAR} ..."
	antlr4 -Dlanguage=Python3 -no-listener -visitor  ${GEN_DIR}/${GRAMMAR}

run:
	${PYTHON} ${SCHEME_INTERPRETER} ${SCHEME_PROGRAM_DIR}/${SCHEME_PROGRAM_ALL} < "${PROGRAM_INPUTS}/${SCHEME_PROGRAM_ALL}"_input.txt > "${PROGRAM_OUTPUTS}/${SCHEME_PROGRAM_ALL}"_output.txt
	diff "${PROGRAM_OUTPUTS}/${SCHEME_PROGRAM_ALL}"_output.txt "${PROGRAM_DIFF_OUTPUTS}/${SCHEME_PROGRAM_ALL}"_output.txt;


clean:
	@echo "Cleaning generated files ..."
	rm -rf ${GEN_DIR}/*.interp ${GEN_DIR}/*.tokens   #Eliminate just special files generated by antlr
	find . -name "__pycache__" -exec rm -rf {} +     #forced remove of files generated to accelerate python execution files
	rm -rf ${PROGRAM_OUTPUTS}

generate_tests:
	@echo "Running tests ..."
	@for test in $(wildcard ${SCHEME_PROGRAM_DIR}/*.scm); do \
  		base=$$(basename $$test .scm); \
  		echo "Running test $$base"; \
  		echo ""${PROGRAM_INPUTS}/$$base"_input.txt"; \
  		python3 ${SCHEME_INTERPRETER} $$test < "${PROGRAM_INPUTS}/$$base"_input.txt > "${PROGRAM_OUTPUTS}/$$base"_output.txt; \
    	diff "${PROGRAM_OUTPUTS}/$$base"_output.txt "${PROGRAM_DIFF_OUTPUTS}/$$base"_output.txt; \
    done

.PHONY: all options setup antlr run clean generate_tests run_features run_try #To specify they are not associated with files